[package]
name = "banderwagon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ed-on-bls12-381-bandersnatch = { git = "https://github.com/arkworks-rs/algebra.git", rev = "da450f98b9b4bf1b4c8eec8f96b4501f9705c517" }
ark-ff = { git = "https://github.com/arkworks-rs/algebra.git", rev = "da450f98b9b4bf1b4c8eec8f96b4501f9705c517"}
ark-ec = { git = "https://github.com/arkworks-rs/algebra.git", rev = "da450f98b9b4bf1b4c8eec8f96b4501f9705c517" }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra.git", rev = "da450f98b9b4bf1b4c8eec8f96b4501f9705c517" }

rayon = {version = "*", optional = true}
hugepage-rs = { version = "0.1.0", optional = true}

[target.'cfg(target_os = "zkvm")'.dependencies]
risc0-zkvm-platform= { version = "2.0.2", features = [
    "unstable",
    "getrandom",
] }
risc0-zkvm = { version = "2.3.1", features = [
    "heap-embedded-alloc",
    "unstable",
] }

[dev-dependencies]
hex = "0.4.3"
rand_chacha = "0.3.1"

[features]
default = ["parallel"]
parallel = ["rayon", "ark-ff/parallel", "ark-ff/asm", "ark-ec/parallel"]
std = ["ark-ff/std"]
enable-hugepages = ["hugepage-rs"]
